export const DEMOGRAPHIC_OPTIONS = {
  race: [
    'Asian',
    'Black/African American',
    'Hispanic/Latino',
    'Middle Eastern',
    'Native American',
    'Pacific Islander',
    'Caucasian',
    'Mixed Race',
    'Prefer not to say',
  ],
  gender: [
    'Male',
    'Female',
    'Non-Binary',
    'Transgender',
    'Other',
    'Prefer not to say',
  ],
  age_group: [
    'Under 18',
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65+',
    'Prefer not to say',
  ],
  religion: [
    'Christian',
    'Muslim',
    'Jewish',
    'Hindu',
    'Buddhist',
    'Sikh',
    'Other',
    'None',
    'Prefer not to say',
  ],
};
