import i18n from '@/i18n';

export const getDemographicOptions = (t = i18n.t.bind(i18n)) => ({
  race: [
    t('onboarding.race_asian'),
    t('onboarding.race_black'),
    t('onboarding.race_hispanic'),
    t('onboarding.race_middle_eastern'),
    t('onboarding.race_native_american'),
    t('onboarding.race_pacific_islander'),
    t('onboarding.race_caucasian'),
    t('onboarding.race_mixed'),
    t('onboarding.prefer_not_to_say'),
  ],
  gender: [
    t('onboarding.gender_male'),
    t('onboarding.gender_female'),
    t('onboarding.gender_non_binary'),
    t('onboarding.gender_transgender'),
    t('onboarding.gender_other'),
    t('onboarding.prefer_not_to_say'),
  ],
  age_group: [
    t('onboarding.age_under_18'),
    t('onboarding.age_18_24'),
    t('onboarding.age_25_34'),
    t('onboarding.age_35_44'),
    t('onboarding.age_45_54'),
    t('onboarding.age_55_64'),
    t('onboarding.age_65_plus'),
    t('onboarding.prefer_not_to_say'),
  ],
  religion: [
    t('onboarding.religion_christian'),
    t('onboarding.religion_muslim'),
    t('onboarding.religion_jewish'),
    t('onboarding.religion_hindu'),
    t('onboarding.religion_buddhist'),
    t('onboarding.religion_sikh'),
    t('onboarding.religion_other'),
    t('onboarding.religion_none'),
    t('onboarding.prefer_not_to_say'),
  ],
  disability: [
    t('onboarding.disability_none'),
    t('onboarding.disability_mobility'),
    t('onboarding.disability_visual'),
    t('onboarding.disability_hearing'),
    t('onboarding.disability_cognitive'),
    t('onboarding.disability_other'),
  ],
});